apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e3ot0toy6-nodejs
  janus-idp.io/tekton: e3ot0toy6-nodejs
  backstage.io/kubernetes-id: e3ot0toy6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e3ot0toy6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
