apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e3ot0toy6-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e3ot0toy6-nodejs 
  name: e3ot0toy6-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e3ot0toy6-nodejs 
